# Generated by Django 3.2 on 2021-04-14 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210414_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 11, 19, 56, 303503)),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 11, 19, 56, 303503)),
        ),
    ]
