# Generated by Django 3.2 on 2021-04-15 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210414_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 12, 22, 35, 111572)),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 12, 22, 35, 111602)),
        ),
    ]
